<a href="https://colab.research.google.com/github/DenisaSei/Git-a-GitHub---David--etek/blob/master/Kopie_se%C5%A1itu_Lambda_funkce.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# definice funkce
def sum_numbers(cislo_1, cislo_2, cislo_3):
  return cislo_1 + cislo_2 + cislo_3

In [ ]:
#volání funkce
sum_numbers(5, 10, 20)

35

In [ ]:
#volání funkce
sum_numbers(1, 5, 7)

13

In [ ]:
import pandas as pd

In [ ]:
tabulka = pd.read_csv("winequalityN.csv")

In [ ]:
tabulka

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.270,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,white,6.3,0.300,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,white,8.1,0.280,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,red,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
6493,red,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,NaN,11.2,6
6494,red,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
6495,red,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
6496,red,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [ ]:
tabulka["type"].unique()

array(['white', 'red'], dtype=object)

In [ ]:
def preloz_vino(typ_vina):
  if typ_vina == "white":
    return "bílé"
  elif typ_vina == "red":
    return "červené"
  else:
    print("neznám")
    return ""

In [ ]:
tabulka["type"].apply(lambda x: "bílé" if x == "white" else "červené")

0          bílé
1          bílé
2          bílé
3          bílé
4          bílé
         ...
6492    červené
6493    červené
6494    červené
6495    červené
6496    červené
Name: type, Length: 6497, dtype: object